### ISSUE TITLE
Handling of PAR region

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ClinCNV#12]
PAR region in males is called with CN=2.
This should be corrected, otherwise we might miss deletions.

![grafik](https://user-images.githubusercontent.com/5638144/62203742-0b6d0c00-b38c-11e9-847e-b5774e4ffe7d.png)

**Comment by GermanDemidov** [comment]
Fixed so far with the --par flag. Waiting for the test results. Not closing the issue until the tests will be positive.
