### ISSUE TITLE
somatic run error

### ISSUE THREAD

**Issue by milkcookie** [imgag/ClinCNV#18]
Hi dear all:
when I run ClinCNV， there was a error flow:
![image](https://user-images.githubusercontent.com/20792140/69691676-bc04d580-110a-11ea-88da-e72a9734290a.png)

any suggestions? thanks

**Comment by GermanDemidov** [comment]
Hi,

our research team also encountered this error several days ago, I am on it, hopefully to fix it today =)

**Comment by GermanDemidov** [comment]
Can you perform git pull now and run again? I think I've fixed it.

I'd strongly recommend to use BAF tracks for somatic calling - using only coverage does not actually improve results comparing to, e.g., cnv-kit.
