### ISSUE TITLE
SEG output: indicate invalid regions

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ClinCNV#19]
Hi German,

could you add information which input regions were skipped because of low quality.
Right now those regions cannot be easily recognized in IGV.
In CnvHunter I added them to the end of the SEG file:
https://github.com/imgag/megSAP/blob/master/test/data/vc_cnvhunter_out1.seg

For example, you could add failed regions to the SEG file and add a "QC" column that contains "qc failed" and some info why. The only drawback would be that you have to assign some CN value, e.g. CN=2 (or 1 for male gonosomes).

I opened a IGV issue to see if we can color the failed regions differently:
https://github.com/igvteam/igv/issues/741

Best,
  Marc

**Comment by GermanDemidov** [comment]
yeap, I am on it, it would be a good improvement

no, we can not color them differently using seg format - I think many people asked it =( many other formats exist for complex formatting - would prefer not to switch there...

**Comment by GermanDemidov** [comment]
Invalid regions are shown as -0.0001 regions (so slightly lower than all the observable dots) and it gives the reason why it was excluded once you point on it with a mouse. needs to be tested.
