### ISSUE TITLE
How to format bed file for WES

### ISSUE THREAD

**Issue by lmanchon** [imgag/ClinCNV#21]
--Hi,

is ClinCNV able to analyse germline WES ? And if yes how to format correctly the bed file ?
The bed file is used to buid the library with the target regions specific to the exome.

Thank you --

**Comment by GermanDemidov** [comment]
Hi,

sure, it is designed for germline WES. It requires 2 files: BED files with coordinates (annotated with GC content) and a coverage file (samples = columns, regions from the bed = rows). More detailed info is here https://github.com/imgag/ClinCNV/blob/master/README.md

**Comment by lmanchon** [comment]
i have a bed file with only 4 fields: chr, start, end, gene_name
but i don't have GC content, how to add this field ?
thank you --

**Comment by GermanDemidov** [comment]
We use ngs-bits for this ( https://github.com/imgag/ClinCNV/blob/master/doc/preliminary_steps.md#generation-of-bed-files-on--and-off-target ) - but the rule is the GC content has to be the 4th column. gene name - the 5th.

**Comment by lmanchon** [comment]
ok, and i need also to generate off-target regions, isn't it ? Is there a tool to generate a plot using the results file ?

**Comment by GermanDemidov** [comment]
I would not generate off-targets for germline exoms. No, only bed and coverage file is enough. (However it's better to have at least tens of samples - ClinCNV does not work for single samples). All the results are visualized in IGV genome browser - you can see the results here https://github.com/imgag/ClinCNV/blob/master/doc/germline_CNV_analysis.md

**Comment by lmanchon** [comment]
--
okay thank you for your help.
At this time i have only one exome and i'm looking for a tool able to analyse single exome, if you have a recommandation or an idea to this task maybe it can help me.

**Comment by GermanDemidov** [comment]
I am afraid this is not really possible =) it is possible for WGS (but limited) but certainly not for exomes. the variability in exomes is huge due to the different hybridization efficiency of probes.
