### ISSUE TITLE
How to prepare WES bed file without ngs-bit ? 

### ISSUE THREAD

**Issue by lmanchon** [imgag/ClinCNV#22]
--hi,

i don't have ngs-bit, is there another tool i can use to prepare this bed file:
https://www.twistbioscience.com/sites/default/files/resources/2019-06/Twist_Exome_Target_hg38.bed
thank you --

**Comment by GermanDemidov** [comment]
Hi, yes, for example

https://www.biostars.org/p/47047/

**Comment by lmanchon** [comment]
ok thank you, i'm going to try with bedtools.
