### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ClinCNV#25]
ClinCnv shows this warning, with R 4.1 which should not be there I guess:

<code>
Stdout of '/mnt/storage1/share/opt/R-4.1.0/bin/Rscript --vanilla /mnt/storage2/GRCh38/share/opt/ClinCNV-1.17.1/clinCNV.R':
[1] "Your R version is too old. We can not guarantee stable work."
</code>

**Comment by GermanDemidov** [comment]
Solved with the commit ae2382e0f3df50bbc5c6909d81c5d83e0bca2c84
