### ISSUE TITLE
Parameter values

### ISSUE THREAD

**Issue by jpuntomarcos** [imgag/ClinCNV#35]
Hi,

Congrats for this useful tool. I have a couple of questions:

- Which is the **recommended value** of **maxNumGermCNVs** parameter for gene panel samples (100-130 genes)? [Here](https://github.com/imgag/ClinCNV/blob/master/doc/germline_CNV_analysis.md) I understand that default is 10000 but 2000 is suggested for WES samples, right?
- Which is the **default value** of **maxNumIter** parameter? I didn’t find it. Do you recommend a specific value for germline calling on gene panel samples (100-130 genes)?

Thanks!

**Comment by GermanDemidov** [comment]
Hi Jose,

thanks a lot! The maxNumGermCNVs is selected according to your sample, some genes are more variable than others, also the number of CNVs is dependent on the scores you use for calling. So simply choose a number starting from which you'd say "that's surely too many CNVs, it must be QC failed". maximum number of iterations I think is 3, but in general 2 should be enough, if something has way too many CNVs and more strict threshold did not help it - I'd say it is a lost case.
