### ISSUE TITLE
error about clinCNV.R :

### ISSUE THREAD

**Issue by kaqisekuzi** [imgag/ClinCNV#39]
Hi @GermanDemidov @marc-sturm @bondarevts @jakobmatthes @Fohlen 
    
     I got a problem , when I run clincnv.R . 
    Do you have any suggestions for a solution?

    `$Rscript $ClinCNV/clinCNV.R  \
        --bed $prepare/gcAnnotated.preparedBedHg38.bin50000.bed \
        --normal $prepare/merge_result/merge_S17.cov \
        --folderWithScript $ClinCNV \
        --scoreG 50 \
        --numberOfThreads 10 \
        --out $result/clincnv_prepare_result
`
There is error message:
`[1] "We run script located in folder /hwfssz1/CS_CELL/cs_cell/marui1/software/ClinCNV . Please, specify ABSOLUTE paths, relative paths do not work for every machine. If everything crashes, please, check the correctness of this path first."
[1] "START cluster allocation."
[1] "Cluster allocated."
[1] "END cluster allocation."
[1] "We are started with reading the coverage files and bed files 2023-03-23 11:33:33"
[1] "Started basic quality filtering. 2023-03-23 11:33:35"
[1] "Amount of regions after filtering of 0-covered regions 98.565"
[1] "Coordinates in BED file are outside of the cytobands! Please check if your cytobands file matches your reference genome version!"
`

Thanks

**Comment by marc-sturm** [comment]
I guess you forgot the --hg38 flag?

**Comment by kaqisekuzi** [comment]
Yes ! You are right！！
Thank you very much！

**Comment by Fohlen** [comment]
Please stop tagging people with their names under content that is potentially unrelevant for them. This is considered extremely rude. After all, a number of contributors do this in their free time, and are not here as your support team. If that's what you're after, pay people for premium support (/rant)
