### ISSUE TITLE
How to determine the cnv type

### ISSUE THREAD

**Issue by kaqisekuzi** [imgag/ClinCNV#40]
Hi @GermanDemidov @marc-sturm 

 How to determine from the result table whether the type of cnv is deletion or duplication?

thanks!

**Comment by GermanDemidov** [comment]
Hi, there is a column "cn_change", the number there denotes the copy-number change

**Comment by kaqisekuzi** [comment]
Yes, I noticed a column of information. 
In my results, the value of "cn_change" is between 1-8, how much is deletion ? Does a value of 1 count as deletion ? Are values greater than 1 counted as duplication?

**Comment by GermanDemidov** [comment]
It depends on ploidy of your organism

**Comment by kaqisekuzi** [comment]
Ok ，thank you very much !!!!
My organism is human, diploid.
That's 2 as the cutoff, right?
