### ISSUE TITLE
Error in 1:ncol(coverages) : argument of length 0 Calls: gc_and_sample_size_normalise

### ISSUE THREAD

**Issue by kaqisekuzi** [imgag/ClinCNV#41]
Hi @marc-sturm 

When I run 1 sample, I got this error.
May I ask if this tool is not suitable for a single sample?

![image](https://user-images.githubusercontent.com/59284758/231402739-f45411a3-2909-4f6d-9a67-74356156a0eb.png)

**Comment by GermanDemidov** [comment]
https://github.com/imgag/ClinCNV#about-this-software
