### ISSUE TITLE
Feature request: add to conda

### ISSUE THREAD

**Issue by matthdsm** [imgag/ClinCNV#43]
Hi,

Would you be able to add your tool to bioconda? This would increase visibility and ease of use tremendously.

Conda packages also come with a free docker image in `biocontainers`, which is good for reproducability.

Thanks
M

**Comment by GermanDemidov** [comment]
Hi, probably I would be able to do this!

**Comment by matthdsm** [comment]
Thanks! Can you leave a comment when it's done?

**Comment by GermanDemidov** [comment]
will totally do!

**Comment by GermanDemidov** [comment]
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/clincnv here it is!

**Comment by matthdsm** [comment]
Wonderful! Thank you very much!

cc @ToonRosseel
