### ISSUE TITLE
Error in 1:ncol(toyCoverageGermlineCohort) : argument of length 0   Calls: source -> withVisible -> eval -> eval

### ISSUE THREAD

**Issue by limww** [imgag/ClinCNV#44]
Hi, 
I am running germline analysis for 40 samples on hg38 reference genome. The normal run (clinCNV.R --normal normal.cov --out outputFolder --bed annotatedBedFile.bed) without including offtarget regions works fine but when I add offtarget parameters then it has the following error.
![image](https://github.com/imgag/ClinCNV/assets/97278512/3044d079-7ef7-4a3a-95c6-baf276bb462c)
 
Run command: 
clinCNV.R --normal normal.cov --bed annotatedBedFile.bed --out outputFolder--normalOfftarget offtarget.cov --bedOfftarget annotatedBedFile_offtarget.bed --numberOfThreads 4  --hg38 

Note: The bedfile was annotated with ngs-bits BedAnnotateGC and BedAnnotateGenes. Not path issue as the cov files and bedfiles can be read. 

Does anyone know what went wrong? 
Thanks :)

**Comment by GermanDemidov** [comment]
Hi, happens here https://github.com/imgag/ClinCNV/blob/1578c9ff1cfc2daf5b65a9c6d9fd9ce67284892c/germline/germlineSolver.R . Could it be that you have a lot of females or vice versa in your cohort?

**Comment by limww** [comment]
Hi @GermanDemidov 
Thanks for the prompt reply! 
Yes, seems like it. The gender estimation is 23 female and 17 males. Does the genders need to be balance then?

**Comment by GermanDemidov** [comment]
No, actually this is fine, I expected maybe 39 females and 1 male...

Could you put 

`print(head(toyCoverageGermlineCohort)) `

just after `toyCoverageGermlineCohort = coverage.normalised[which_to_allow_ontarget,]` (line 282)

and run the tool once again?

**Comment by limww** [comment]
I added the print line to the germlineSolver.R. 
[1] "Calling started 2023-07-14 09:46:36.416317"
[1] "Working with germline sample RP0401 2023-07-14 09:46:37.14366"
           RP0401   RP0406    RP0407   RP0408       RP0409       RP0410
2177 1.073465e+00 1.026849 1.0264345 1.099993 4.806612e-01 7.672907e-01
2178 1.380899e+00 1.524678 0.9007097 1.072173 1.599141e-10 1.540920e-01
2179 1.256461e+00 1.140734 0.9768659 1.027922 1.229222e-01 1.818983e-10
2183 2.715974e-10 1.228536 0.8708971 1.212438 1.196760e+00 9.050612e-01
2185 1.644984e-10 1.208829 0.8612478 1.287081 1.385536e+00 1.101127e+00

**Comment by GermanDemidov** [comment]
Ah so! So the calling actually started and it kinda works - but it fails at some later point.

Could you maybe print chromosome where the error happens? Don't your bed file contain any weird chromosomes except chr1-21, chrX/chrY? Line 185, `chrom = names(left_borders)[l]`, could you print this chromosome and tell me at which chromosome the tool fails?

**Comment by limww** [comment]
stops running at chr22, I removed contigs from offtarget bedfiles and there are no contigs in my normal bedfile either. 
[1] "Calling started 2023-07-14 10:02:09.88987"
[1] "Working with germline sample RP0401 2023-07-14 10:02:10.62412"
[1] "chr1"
[1] "chr10"
[1] "chr11"
[1] "chr12"
[1] "chr13"
[1] "chr14"
[1] "chr15"
[1] "chr16"
[1] "chr17"
[1] "chr18"
[1] "chr19"
[1] "chr2"
[1] "chr20"
[1] "chr21"
           RP0401   RP0406    RP0407   RP0408       RP0409       RP0410
2177 1.073465e+00 1.026849 1.0264345 1.099993 4.806612e-01 7.672907e-01
2178 1.380899e+00 1.524678 0.9007097 1.072173 1.599141e-10 1.540920e-01
2179 1.256461e+00 1.140734 0.9768659 1.027922 1.229222e-01 1.818983e-10
2183 2.715974e-10 1.228536 0.8708971 1.212438 1.196760e+00 9.050612e-01
2185 1.644984e-10 1.208829 0.8612478 1.287081 1.385536e+00 1.101127e+00
2186 1.090887e-10 1.153807 0.8461273 1.218920 1.226202e+00 1.059202e+00
......
[1] "chr22"
   RP0401    RP0406    RP0407    RP0408    RP0409    RP0410 
0.9954706 0.8325012 1.0896545 1.1011779 1.0033081 1.0593482 
Error in 1:ncol(toyCoverageGermlineCohort) : argument of length 0
Calls: source -> withVisible -> eval -> eval
Execution halted

**Comment by GermanDemidov** [comment]
I see what happened. Looks like there is only one "reasonable" probe on chr22 (probably left arm? which is very short and unmappable). Do you have any regions with coordinates less than 15 millions in your bed file? I'd better remove everything which is on the left arm of chr22.

Alternatively (and faster) - you can change code (the line you know, 282 in the original file)

`toyCoverageGermlineCohort = coverage.normalised[which_to_allow_ontarget,]`

to

`toyCoverageGermlineCohort = coverage.normalised[which_to_allow_ontarget,,drop=F]`

**Comment by limww** [comment]
Hi @GermanDemidov, The problem is solved. Thanks a lot for your help! :)
