### ISSUE TITLE
[Ends of chrom] argument is of length zero 

### ISSUE THREAD

**Issue by RochaLAJ** [imgag/ClinCNV#47]
During our run we obtained the following error message 

![image](https://github.com/imgag/ClinCNV/assets/43121804/f9cb29e4-7013-4587-912b-38de0ff7d2f4)

Our data is composed by one single WGS aligned with BWA using GRCh38.p14 as reference. 
BED and COV files were prepared as recommended in the readme.md 

Any suggestion?

**Comment by GermanDemidov** [comment]
Hi, ClinCNV does not work with single samples, it requires a cohort for normalization. The error seems to be unrelated, but such a use case is not possible anyway.

**Comment by RochaLAJ** [comment]
Thank you!
