### ISSUE TITLE
Order of the output CNVs

### ISSUE THREAD

**Issue by axelgschwind** [imgag/ClinCNV#8]
Hi,

I suggest we order the output CNVs exactly as they are ordered in the input Bed file or cov files respectively.

**Comment by GermanDemidov** [comment]
I can do it but why? I do not expect input bed files to be ordered so I have to re-order them - ClinCNV needs to work with adjacent windows, the data is organised in arrays, not in hashmaps. I can re-order final CNVs according to the order of input bed file - but it is totally the same as re-order them post factum.
